### ISSUE TITLE
Ask for GH org too

### ISSUE THREAD

**Issue by richfitz** [metacran/mason.rpkg#1]
Related to 22e4cf2387683570c5f0d68b2ec9fb6d7e93739e, it might be worth doing this as:

GitHub username:

then

GitHub account to store the repository (with default being username)

I often create repositories that are not on my account but some lines (well, really just the copyright one at the bottom of the README) need the username, and others want the place where the package will reside.

**Comment by gaborcsardi** [comment]
Moved to https://github.com/metacran/mason.github/issues/5

(Sorry moving around the repos a bit, I'll have a basic package, and the old one will be the github template.)
